### PR TITLE
PGN Stream Parser, Parallel Hash Map, GZip Lib

### PR DESCRIPTION
**Pull request by Disservin**
Feel free to test ;) 

I think the current approach should already work, I'm still probably gonna worka bit on the chess-lib's api for the parser.

So this includes a few changes, first an entirely new pgn parsing, which is visitor based, for this I also had to update the gzip library because the previous implementation seemed to have some problems. This is also includes the parallel hash map from https://github.com/greg7mdp/parallel-hashmap.

Local results show
```
Looking (recursively) for pgn files in pgns
Found 11700 .pgn(.gz) files, creating 128 chunks for processing.
Progress: 128/128
Time taken: 23s
Wrote 381153241 scored positions to scoreWDLstat.json for analysis.
```

vs 

```
Looking (recursively) for pgn files in pgns
Found 11700 .pgn(.gz) files, creating 128 chunks for processing.
Progress: 128/128
Time taken: 8.428s
Wrote 381153241 scored positions to scoreWDLstat.json for analysis.
```

The speedups can be broken down into:
- The new parser implementation, a few seconds like ~3-5
- The parallel hash map, ~10

### CODE REVIEW

**Comment by robertnurnberg** [comment]
Sadly, for me this is a functional change. Running the update script with master and patch gives this difference.

```diff
diff master.log scoreWDLstat.log 
4,10c4,6
Progress: 1/96Error when parsing: pgns/23-09-11/64feb4562cd016da89ab5e14/64feb4562cd016da89ab5e14-59.pgn.gz at game index 174
< basic_ios::clear: iostream error
Progress: 8/96Error when parsing: pgns/23-09-11/64fecc8d2cd016da89ab6137/64fecc8d2cd016da89ab6137-77.pgn.gz at game index 142
< basic_ios::clear: iostream error
Progress: 94/96
< Time taken: 141s
< Wrote 711039015 scored positions to updateWDL.json for analysis.
---
Progress: 96/96
> Time taken: 105.938s
> Wrote 2318931161 scored positions to updateWDL.json for analysis.
```

**Comment by Disservin** [comment]
> Sadly, for me this is a functional change. Running the update script with master and patch gives this difference.
> 
> ```diff
> diff master.log scoreWDLstat.log 
> 4,10c4,6
> Progress: 1/96Error when parsing: pgns/23-09-11/64feb4562cd016da89ab5e14/64feb4562cd016da89ab5e14-59.pgn.gz at game index 174
> < basic_ios::clear: iostream error
> Progress: 8/96Error when parsing: pgns/23-09-11/64fecc8d2cd016da89ab6137/64fecc8d2cd016da89ab6137-77.pgn.gz at game index 142
> < basic_ios::clear: iostream error
> Progress: 94/96
> < Time taken: 141s
> < Wrote 711039015 scored positions to updateWDL.json for analysis.
> ---
> Progress: 96/96
> > Time taken: 105.938s
> > Wrote 2318931161 scored positions to updateWDL.json for analysis.
> ```
> 
> The full log looks like this: [master.log](https://github.com/official-stockfish/WDL_model/files/12872938/master.log)

That cant be. In the current state `at game index 142` is no longer there.

**Comment by robertnurnberg** [comment]
Oh, sorry. Maybe I didn't update my fork to latest master. Will recheck once I'm at home.

**Comment by robertnurnberg** [comment]
So I can confirm that locally I am on `2ae2ef2ad2e3f135d7154e2d4c01e747d8a893aa`, which is master.

Note that the backspace encodings (?) in the logs probably messed up the `diff` output. I attach the log from your patch here: [patch.log](https://github.com/official-stockfish/WDL_model/files/12873722/patch.log).

If you give me some time I can upload my pgn collection to google and share the link here.

**Comment by robertnurnberg** [comment]
With latest fix:
```
> diff master.log patch.log 
4,10c4,6
Progress: 1/96Error when parsing: pgns/23-09-11/64feb4562cd016da89ab5e14/64feb4562cd016da89ab5e14-59.pgn.gz at game index 174
< basic_ios::clear: iostream error
Progress: 8/96Error when parsing: pgns/23-09-11/64fecc8d2cd016da89ab6137/64fecc8d2cd016da89ab6137-77.pgn.gz at game index 142
< basic_ios::clear: iostream error
Progress: 94/96
< Time taken: 141s
< Wrote 711039015 scored positions to updateWDL.json for analysis.
---
Progress: 96/96
> Time taken: 91.451s
> Wrote 711038924 scored positions to updateWDL.json for analysis.
```

So I guess the difference could be due to those two corrupted files?

**Comment by Disservin** [comment]
Can you upload these two pgns separately?

**Comment by Disservin** [comment]
@robertnurnberg I pushed some other smaller lib changes, these shouldnt cause any issue, at least locally none. 
If you want you can also give some feedback on the libraries api for the new pgn parser. Better suited names or other changes.

I will wait with this until @vondele  has tested it with his pgns, which could take some time because I think he's busy right now. 
Just as a heads up this approach will actually read more from corrupted pgns, so if your pgn collection contains corrupted pgns then the scored positions are expected to be slightly different. Just rename them to `.broken` if that's the case.

**Comment by robertnurnberg** [comment]
For me this is still non-functional, so all good. Regarding the API, I have no strong views and would just trust your judgement.

In general a nice speedup, well done.

**Comment by vondele** [comment]
This looks good to me, I'd like to ask reducing this to three commits or so (maybe even separate PRs)

* gzip changes
* hashmap changes
* chess lib changes

That will make it a bit easier if we have to fix things in the future, and for backporting to the popularpos repo...

For the hashmap, I'm a bit surprised that this would be a speedup, in particular when analyzing a lot of data. In principle, our main branch uses independent maps per thread, i.e. lock free, while now we have a shared map that is locked as needed. We do save the merging step, but it costs during analysis. It is probably cleaner to have the shared map (less memory use, and one less step), nevertheless.

**Comment by robertnurnberg** [comment]
I agree that three separate PRs would be ideal, for what it's worth.

**Comment by Disservin** [comment]
moving discussion to #80

**Pull request closed without merging**
