### PR TITLE
new pgn reader

### PR DESCRIPTION
**Pull request by Disservin**
- Third PR for #76

### CODE REVIEW

**Comment by Disservin** [comment]
@vondele can you confirm that this works for you too?

**Comment by vondele** [comment]
I'll give it a try right now.

**Comment by vondele** [comment]
Yep, all identical, and a speedup:
```
$ diff masterlogs/scoreWDLstat.log patchlogs/scoreWDLstat.log 
4,5c4,5
Progress: 128/128
< Time taken: 94s
---
Progress: 128/128
> Time taken: 66.366s
```

**Comment by vondele** [comment]
If ready for merging, please undraft.

**Comment by vondele** [comment]
Thanks!

**Comment by robertnurnberg** [comment]
Just to confirm that after this merge things are still non-functional for me. Comparing with 57c7befa748c976a6ea9060f95481e3999c23e5f gives me

```
> diff master.log patch.log 
4,5c4,5
Progress: 94/96
< Time taken: 160s
---
Progress: 96/96
> Time taken: 98.845s
```

**Pull request merged**
