### PR TITLE
allow fitting based on material

### PR DESCRIPTION
**Pull request by robertnurnberg**
This PR allows fitting based on material. (Based on my understanding of the code.)

No functional change for running `python scoreWDL.py` compared to https://github.com/official-stockfish/WDL_model/pull/21.

Attached sample output for the json data from https://github.com/official-stockfish/WDL_model/pull/7#issuecomment-1685286831 with the command 
`python scoreWDL.py scoreWLDstat.json --yData material --yDataMin 5 --yDataMax 78 --yDataTarget 68`.

PS: Of course, the C++ output for SF at this stage makes no sense, as SF is based on move.
WDL_model_summary

### CODE REVIEW

**Comment by robertnurnberg** [comment]
Agreed. But the model contour plots compared to the data look very wrong, not sure if I missed something in the maths behind the code. (I blindly used the same fitting functions and polynomials etc. as for moves)

The conflict was probably the `mom` change line 192, should be fixed after my forced push.

**Comment by vondele** [comment]
It is potentially correct, the fits of the as and bs is probably not quite able to fit the low material part of the data, which propagates into the higher material part of the data. Restricting the fit to material > 10 or even 15 could work (or maybe providing much more data).

**Comment by vondele** [comment]
I think the other interesting bit is that the cross-section at material 68 shows much better win rates than the model for eval near 0.

**Comment by robertnurnberg** [comment]
I picked 68 completely at random (thinking was 1 minor piece and 2 paws exchanged on each side). :)

**Comment by vondele** [comment]
so, with a little larger `--yDataMin 10` the data and  the model contour plots look pretty reasonable.
WDL_model_summary
This looks OK, and the code already looks much cleaner now.
Thanks!

**Pull request merged**
