### PR TITLE
improve error handling

### PR DESCRIPTION
**Pull request by robertnurnberg**
Output errors we encounter when trying to download pgn files. Skip remaining downloads for a test as soon as we get an HTTP error code.

Fixes https://github.com/official-stockfish/WDL_model/issues/32.

### CODE REVIEW

**Comment by vondele** [comment]
as mentioned elsewhere, I think there are cases where a pgn might be missing for 1 task, but pgns for other tasks are present (like when a worker would have a problem sending the pgn, or is stopped before).

**Comment by robertnurnberg** [comment]
So you prefer not to `break`?

**Comment by robertnurnberg** [comment]
For the example from https://github.com/official-stockfish/WDL_model/issues/32 _all_ the pgn's are missing, I think.

**Comment by robertnurnberg** [comment]
Could have a counter, say 3, and break once 3 pgn's are missing?

**Comment by robertnurnberg** [comment]
With the latest change a third missing task per test means the test gets skipped. cli option `--leniency` can be used to be more or less lenient. 

Also made `--help` a bit more informative.

**Comment by robertnurnberg** [comment]
Final version is more lenient: only count _consecutive_ HTTP errors, and allow 3 of those before skipping.

**Pull request merged**
