### PR TITLE
minor cleanup and variable renaming

### PR DESCRIPTION
**Pull request by robertnurnberg**
This is a minor cleanup of the recent changes to the python script.

I also took the chance to make the variable names consistent with the readme, in particular now the name `score` is no longer ambiguous. 

Up to rounding errors the changes are non-functional for me.

PS: The rounding errors could be down to the change from `math.log` to `np.log`, but not sure.

### CODE REVIEW

**Comment by vondele** [comment]
I think consistency is good, now the script is called scoreWDL ... this ambiguity between eval / score etc is hard to avoid, there is no real consistent usage. But cleanups look good to me. I agree that math.log and np.log can cause the difference (maybe float vs float64)

**Comment by robertnurnberg** [comment]
I think the script name is fine, as in a very wide sense we are "scoring" data. :)

**Comment by vondele** [comment]
can you rebase on current master (some small conflicts)?

**Comment by robertnurnberg** [comment]
Sure, after lunch. :)

**Comment by robertnurnberg** [comment]
Resolved conflict with github GUI, but should be fine.

**Pull request merged**
