### PR TITLE
Use np.nan instead of np.NaN

### LINKED ISSUE #197: scoreWDL.py Breaks with Numpy 2.0 due to usage of np.NaN
```
Traceback (most recent call last):
  File "/Users/shawn/WDL_model/scoreWDL.py", line 729, in <module>
    wdl_data.load_json_data(args.filename)
  File "/Users/shawn/WDL_model/scoreWDL.py", line 150, in load_json_data
    self.w_density = np.full_like(total, np.NaN, dtype=float)
                                         ^^^^^^
  File "/Users/shawn/WDL_model/venv/lib/python3.12/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.. Did you mean: 'nan'?
```

### PR DESCRIPTION
**Pull request by xu-shawn**
Fixes #197

### CODE REVIEW

**Comment by robertnurnberg** [comment]
LGTM

**Comment by Disservin** [comment]
mh dunno if we want to now require a version in https://github.com/official-stockfish/WDL_model/blob/master/requirements.txt ?

**Comment by Disservin** [comment]
test

**Comment by xu-shawn** [comment]
> mh dunno if we want to now require a version in https://github.com/official-stockfish/WDL_model/blob/master/requirements.txt ?

This shouldn't require any dependency changes. AFAIK `np.nan` has existed since numpy 1.0

**Comment by robertnurnberg** [comment]
Agree with Shawn. Prior to Numpy 2.0 `np.NaN` (in fact any way to capitalize it) was an accepted alias for `np.nan`.

**Pull request merged**
