### PR TITLE
detect gzipped downloads

### PR DESCRIPTION
**Pull request by robertnurnberg**
Correctly deal with gzip served data. Needs testing.

### CODE REVIEW

**Comment by vondele** [comment]
Just wondering if we can't use the content header for this instead of looking at the magic bytes:
`if response.info().get('Content-Encoding') == 'gzip':`

from https://stackoverflow.com/questions/3947120/does-python-urllib2-automatically-uncompress-gzip-data-fetched-from-webpage

**Comment by robertnurnberg** [comment]
I just thought with current fishtest we could simply rename the tmp file to `.pgn.gz` ? Without any checks. What do you think?

I guess we'll retire this code anyway once bulk download is implemented, so not worth it to spend more time on it?

**Comment by vondele** [comment]
I agree we should retire this after bulk download. So kind of check is not bad. So if you agree, let's just merge that, to be removed as soon as bulk download arrives.

**Comment by robertnurnberg** [comment]
yeah, just merge as is, thanks

**Pull request merged**
