### PR TITLE
add meta data entries and skip SPSA tests

### PR DESCRIPTION
**Pull request by robertnurnberg**
As discussed. Also sort the json keys alphabetically.

### CODE REVIEW

**Comment by robertnurnberg** [comment]
Just saw this https://github.com/official-stockfish/WDL_model/pull/40#issuecomment-1712839184, so will update this PR.

**Comment by vondele** [comment]
meanwhile, I also realized that the spsa tests could be identified from the metadata as well (there is an spsa field), and we could skip downloading pgns, as there are none for these tests.

**Comment by robertnurnberg** [comment]
Hm, so where exactly do I find the new and base sha's on e.g. https://tests.stockfishchess.org/tests/view/64fc104f5a91a84763528cd2 ?

**Comment by robertnurnberg** [comment]
And can you send me example html with spsa flag in it?

**Comment by vondele** [comment]
https://tests.stockfishchess.org/tests/view/64f31a78a0f9f22deb74cb07

**Comment by vondele** [comment]
```
Collecting meta data for test 64f31a78a0f9f22deb74cb07 ...
Could not find sprt information at https://tests.stockfishchess.org/tests/view/64f31a78a0f9f22deb74cb07.
Downloading pgns to ./pgns/23-09-02/64f31a78a0f9f22deb74cb07/ ...
  Fetching 1136 missing pgns ...
  HTTP Error 404 occurred for URL: http://tests.stockfishchess.org/api/pgn/64f31a78a0f9f22deb74cb07-1135.pgn
  HTTP Error 404 occurred for URL: http://tests.stockfishchess.org/api/pgn/64f31a78a0f9f22deb74cb07-1134.pgn
  HTTP Error 404 occurred for URL: http://tests.stockfishchess.org/api/pgn/64f31a78a0f9f22deb74cb07-1133.pgn
  HTTP Error 404 occurred for URL: http://tests.stockfishchess.org/api/pgn/64f31a78a0f9f22deb74cb07-1132.pgn
  Skipping remaining pgns of test 64f31a78a0f9f22deb74cb07 ...
```

**Comment by vondele** [comment]
> Hm, so where exactly do I find the new and base sha's on e.g. https://tests.stockfishchess.org/tests/view/64fc104f5a91a84763528cd2 ?

resolved_new/resolved_base I think.... but they are short sha for now.

**Comment by robertnurnberg** [comment]
Exactly, so better to rely on engine names in .pgn?

**Comment by robertnurnberg** [comment]
I guess the https links for base_tag and new_tag would work?

**Comment by robertnurnberg** [comment]
```
{
    "adjudication": "True",
    "base_net": "nn-c38c3d8d3920.nnue",
    "base_options": "Hash=64",
    "base_tag": "<a href=\"https://github.com/Vizvezdenec/Stockfish/commit/b25d68f6ee2d016cc0c14b076e79e6c44fdaea2a\" target=\"_blank\" rel=\"noopener\">",
    "book": "UHO_4060_v2.epd",
    "book_depth": "8",
    "last updated": "2023-09-09 10:36:52",
    "new_net": "nn-c38c3d8d3920.nnue",
    "new_options": "Hash=64",
    "new_tag": "<a href=\"https://github.com/Vizvezdenec/Stockfish/commit/7ed5267fa71c2ca7433077e2737cf97db0f2e68d\" target=\"_blank\" rel=\"noopener\">",
    "new_tc": "60+0.6",
    "sprt": "elo0: 0.50 alpha: 0.05 elo1: 2.50 beta: 0.05 state: rejected (normalized)",
    "start time": "2023-09-09 06:27:27",
    "tc": "60+0.6",
    "threads": "1"
}
```

The tags are a bit ugly for now, but could be changed later (or beatified with current API work on fishtest server side).

**Pull request merged**
