### PR TITLE
suptitle

### PR DESCRIPTION
**Pull request by robertnurnberg**
Change the `suptitle` (could also just write "WDL"?) and applied black.

Btw, what is the easiest way to obtain the latest file `scoreWLDstat.json`? If I had it, I could update the `pgn` as well.

### CODE REVIEW

**Comment by vondele** [comment]
no easy way to have the json, it is quite large.

**Comment by vondele** [comment]
I've made a copy of data available, for testing, basically current master https://drive.google.com/file/d/1ckSG8g37u9b5ZONoBwG5virYlrb0kFE6/view?usp=sharing

**Comment by robertnurnberg** [comment]
Thanks. Will download and test later.

**Comment by robertnurnberg** [comment]
Using the data I get this plot, which differs from master. (Check polynomial at bottom left.)

Is the fitting deterministic?
WDL_model_summary

**Comment by vondele** [comment]
yeah, it is a different data set (i.e. August data).

**Pull request merged**
