### PR TITLE
allow parsing of .pgn.gz files

### PR DESCRIPTION
**Pull request by robertnurnberg**
Draft for now, may need some testing.

A future refactoring could try to drop the external lib.

In theory the local collections of .pgn's we each have can now be converted to .pgn.gz.

### CODE REVIEW

**Comment by robertnurnberg** [comment]
This needs https://github.com/official-stockfish/WDL_model/pull/65 to compile.

**Comment by Disservin** [comment]
i was running into issues on windows, with this approach not reading the entire file... this more simple version works fine for me https://github.com/Disservin/WLD_model/tree/gzip-simple, performance can probably be improved

**Comment by robertnurnberg** [comment]
Excellent, thanks. A much simpler solution. A quick test for me indicates it works as intended.

Will undraft for review.

**Comment by robertnurnberg** [comment]
Undrafted. I have kept the commit history intact for now, but probably best to squash before merging. So let me know when I should squash.

**Review by Disservin — APPROVED** [review]
LGTM

Tested on windows and ubuntu.

**Comment by robertnurnberg** [comment]
Thanks. Squashed into a single commit.

**Comment by Disservin** [comment]
> Thanks. Squashed into a single commit.

wasnt really required anyway, since we can merge with squash? (and keep the correct co authorship)

**Comment by robertnurnberg** [comment]
Oh, sorry. That wasn't my intention at all. If there is any way to restore your co-authorship, please go ahead.

In fact I thought this PR was a very nice team effort. 👍

**Comment by Disservin** [comment]
I know ;) all good I don’t mourn the missing co authorship ^^

**Comment by vondele** [comment]
> i was running into issues on windows, with this approach not reading the entire file... this more simple version works fine for me https://github.com/Disservin/WLD_model/tree/gzip-simple, performance can probably be improved

actually, I'm running in an issue with this trying to analyze the lichess db... a single file is 30GB compressed, so no way I can keep the full uncompressed file in memory. This would be a use case where reading from the file incrementally would be beneficial.

**Comment by Disservin** [comment]
Oh well, I imagined something like this happen...

**Pull request merged**
