### PR TITLE
gzip stream

### PR DESCRIPTION
**Pull request by Disservin**
i think this should avoid reading the entire file into memory

### CODE REVIEW

**Comment by vondele** [comment]
can confirm this works at least correctly in giving the right results for the fishtest pgns. 
I can't test on the lichess pgns, as that seems a pgn format that can't be parsed right now... but the fact it fails immediately sounds good.

For reference, that's how such a lichess pgn looks like:
```
[Event "Rated Blitz game"]
[Site "https://lichess.org/ksGjiqOM"]
[Date "2023.02.01"]
[Round "-"]
[White "samur1212"]
[Black "Behemothh"]
[Result "0-1"]
[UTCDate "2023.02.01"]
[UTCTime "00:00:21"]
[WhiteElo "1539"]
[BlackElo "1481"]
[WhiteRatingDiff "-7"]
[BlackRatingDiff "+6"]
[ECO "B23"]
[Opening "Sicilian Defense: Closed"]
[TimeControl "300+3"]
[Termination "Normal"]

1. e4 { [%eval 0.36] [%clk 0:05:00] } 1... c5 { [%eval 0.32] [%clk 0:05:00] } 2. Nc3 { [%eval 0.24] [%clk 0:05:02] } 2... d6 { [%eval 0.0] [%clk 0:04:54] } 3. Bc4 { [%eval 0.0] [%clk 0:05:04] } 3... Nc6 { [%eval 0.2] [%clk 0:04:54] } 4. d3 { [%eval -0.32] [%clk 0:05:05] } 4... Nf6 { [%eval -0.03] [%clk 0:04:39] } 5. Nge2 { [%eval -0.4] [%clk 0:05:06] } 5... a6?! { [%eval 0.43] [%clk 0:04:36] } 6. a4?! { [%eval -0.34] [%clk 0:05:08] } 6... e6 { [%eval -0.4] [%clk 0:04:28] } 7. O-O { [%eval -0.13] [%clk 0:05:09] } 7... Be7 { [%eval -0.14] [%clk 0:04:30] } 8. f4?! { [%eval -0.8] [%clk 0:05:11] } 8... O-O { [%eval -0.71] [%clk 0:04:23] } 9. f5?! { [%eval -1.59] [%clk 0:05:05] } 9... Kh8? { [%eval -0.1] [%clk 0:03:21] } 10. Ng3?! { [%eval -0.8] [%clk 0:05:02] } 10... d5 { [%eval -0.62] [%clk 0:03:12] } 11. exd5?! { [%eval -1.42] [%clk 0:05:03] } 11... exd5 { [%eval -1.33] [%clk 0:03:13] } 12. Ba2 { [%eval -1.23] [%clk 0:05:02] } 12... h6 { [%eval -0.84] [%clk 0:02:40] } 13. Nh5 { [%eval -0.96] [%clk 0:04:59] } 13... Qd6?? { [%eval 2.41] [%clk 0:01:51] } 14. Nxf6 { [%eval 2.08] [%clk 0:04:59] } 14... Bxf6 { [%eval 2.42] [%clk 0:01:50] } 15. Bxd5?? { [%eval -4.0] [%clk 0:04:58] } 15... Be5?? { [%eval 2.1] [%clk 0:01:38] } 16. g3?? { [%eval -4.74] [%clk 0:04:53] } 16... Bxc3 { [%eval -4.53] [%clk 0:01:17] } 17. Bxc6?? { [%eval -8.91] [%clk 0:04:51] } 17... Bd4+ { [%eval -8.81] [%clk 0:01:18] } 18. Kh1 { [%eval -9.0] [%clk 0:04:41] } 18... Qxc6+ { [%eval -8.92] [%clk 0:01:19] } 19. Rf3 { [%eval -11.65] [%clk 0:04:43] } 19... Bxf5 { [%eval -10.62] [%clk 0:01:17] } 20. Qf1 { [%eval -15.08] [%clk 0:04:36] } 20... Bg4 { [%eval -15.55] [%clk 0:01:18] } 21. Kg2 { [%eval -16.46] [%clk 0:04:31] } 21... Rae8 { [%eval -17.47] [%clk 0:01:07] } 22. Bd2?! { [%eval #-5] [%clk 0:04:25] } 22... Bxf3+ { [%eval #-4] [%clk 0:00:58] } 23. Qxf3 { [%eval #-4] [%clk 0:04:27] } 23... Qxf3+? { [%eval -8.47] [%clk 0:01:00] } 24. Kxf3 { [%eval -8.37] [%clk 0:04:29] } 24... Re7 { [%eval -8.66] [%clk 0:00:50] } 25. Kg2 { [%eval -13.07] [%clk 0:04:29] } 25... Rfe8 { [%eval -9.77] [%clk 0:00:52] } 26. Kh3 { [%eval -8.79] [%clk 0:04:20] } 26... Re2 { [%eval -9.28] [%clk 0:00:53] } 27. Bf4 { [%eval -12.17] [%clk 0:04:22] } 27... Rxc2 { [%eval -10.15] [%clk 0:00:50] } 28. b3 { [%eval -17.38] [%clk 0:04:23] } 28... Bxa1 { [%eval -17.87] [%clk 0:00:52] } 29. Kg4 { [%eval -17.93] [%clk 0:04:24] } 29... Rxh2 { [%eval -18.0] [%clk 0:00:39] } 30. Bc7 { [%eval -19.25] [%clk 0:04:23] } 30... Ree2 { [%eval #-5] [%clk 0:00:40] } 31. Bd6 { [%eval #-5] [%clk 0:04:19] } 31... Bd4 { [%eval #-5] [%clk 0:00:38] } 32. Bf4 { [%eval #-5] [%clk 0:04:19] } 32... g6 { [%eval #-4] [%clk 0:00:33] } 33. Bc7 { [%eval #-2] [%clk 0:04:20] } 33... f5+ { [%eval #-1] [%clk 0:00:34] } 34. Kf4 { [%eval #-1] [%clk 0:04:21] } 34... Rhf2# { [%clk 0:00:33] } 0-1
```
I think the fact it has `?!` etc after the moves might confuse the parser?

**Comment by Disservin** [comment]
Okay, yeah the parser was written for minial cutechess pgns, the kind we get from fishtest. I will later test this on windows and merge. 
It seems the parser needs some work in the future.

**Comment by robertnurnberg** [comment]
> Okay, yeah the parser was written for minial cutechess pgns, the kind we get from fishtest. I will later test this on windows and merge. It seems the parser needs some work in the future.

For now just removing any `"!"` and/or `"?"` at the end of the SAN move may already be enough?

**Comment by Disservin** [comment]
Mh the pgn posted by @vondele even works for me
```cpp
#include "./chess.hpp"

using namespace chess;

int main(int argc, char const* argv[]) {
    auto file_stream = std::ifstream("test.txt");

    auto game = pgn::readGame(file_stream);

    Board board;
    for (const auto& move : game.value().moves()) {
        std::cout << uci::moveToUci(move.move) << std::endl;
        board.makeMove(move.move);
    }

    return 0;
}
```

**Comment by vondele** [comment]
so, must be something else in that pgn... Let me try to figure it out, adding and improving the exception handling.

**Comment by vondele** [comment]
OK, clear now..
```
Error when parsing: /mnt/md0/chess/lichessgames/2023/lichess_db_standard_rated_2023-02.pgn.gz at game index 31
Illegal San, Step 4: O-O? r1b1kbnr/ppp1qpp1/2np3p/8/Q1BPPp1P/2P2N2/PP4P1/RNB1K2R w KQkq - 1 9
```
aka:
```
[Event "Rated Rapid game"]
[Site "https://lichess.org/BESHtSR7"]
[Date "2023.02.01"]
[Round "-"]
[White "Jorge_1907"]
[Black "sevket_k"]
[Result "1-0"]
[UTCDate "2023.02.01"]
[UTCTime "00:00:13"]
[WhiteElo "1947"]
[BlackElo "1854"]
[WhiteRatingDiff "+5"]
[BlackRatingDiff "-4"]
[ECO "C34"]
[Opening "King's Gambit Accepted: Fischer Defense"]
[TimeControl "600+5"]
[Termination "Normal"]

1. e4 { [%eval 0.36] [%clk 0:10:00] } 1... e5 { [%eval 0.32] [%clk 0:10:00] } 2. f4? { [%eval -0.71] [%clk 0:10:02] } 2... exf4 { [%eval -0.43] [%clk 0:10:03] } 3. Nf3 { [%eval -0.6] [%clk 0:10:06] } 3... d6 { [%eval -0.51] [%clk 0:10:07] } 4. Bc4 { [%eval -0.61] [%clk 0:10:06] } 4... h6 { [%eval -0.63] [%clk 0:10:10] } 5. h4 { [%eval -0.68] [%clk 0:10:08] } 5... Nc6 { [%eval -0.42] [%clk 0:08:37] } 6. c3? { [%eval -2.21] [%clk 0:10:09] } 6... Na5? { [%eval -1.02] [%clk 0:07:33] } 7. Qa4+ { [%eval -1.25] [%clk 0:09:51] } 7... Nc6 { [%eval -0.82] [%clk 0:07:36] } 8. d4 { [%eval -1.1] [%clk 0:09:51] } 8... Qe7? { [%eval 1.46] [%clk 0:07:09] } 9. O-O? { [%eval -1.42] [%clk 0:09:48] } 9... Nf6?? { [%eval 2.83] [%clk 0:07:01] } 10. Bd5?? { [%eval -1.01] [%clk 0:09:36] } 10... Kd7?? { [%eval 3.48] [%clk 0:06:07] } 11. Bxf4 { [%eval 3.74] [%clk 0:09:31] } 11... g5? { [%eval 5.9] [%clk 0:05:45] } 12. hxg5? { [%eval 4.59] [%clk 0:09:22] } 12... hxg5 { [%eval 5.12] [%clk 0:05:46] } 13. Bxg5 { [%eval 4.83] [%clk 0:09:24] } 13... Bh6 { [%eval 5.27] [%clk 0:05:47] } 14. Bxf6?? { [%eval -1.65] [%clk 0:09:19] } 14... Qxf6?? { [%eval 6.76] [%clk 0:05:44] } 15. Ne5+ { [%eval 6.77] [%clk 0:09:22] } 15... dxe5 { [%eval 8.45] [%clk 0:05:40] } 16. Rxf6 { [%eval 8.58] [%clk 0:09:24] } 1-0

```

**Comment by robertnurnberg** [comment]
Looking quickly at the chess lib code the easiest fix seem to be to just check in `parseSan` if the first 3 chars are `O-O` or `0-0`, or if the first five are `O-O-O` or `0-0-0`. Then also consistent with the rest of the san parsing code it seems. (just read san for as much as you need).

**Comment by robertnurnberg** [comment]
I leave this fix to you, ok? @Disservin 

Just be careful: first check for long castling, so that you do not match a long castling san as a short castling one. ;)

**Comment by vondele** [comment]
I can now also confirm memory usage remains small for ./scoreWDLstat while parsing the big gzipped file. So this works from my POV.

**Comment by Disservin** [comment]
Just tested this on windows too and the streaming works just fine. I will fix the chess library after this.

**Pull request merged**
